// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFtTFtOTfPCERjKlnOibTrTJywMNWsEI0',
    appId: '1:571856118326:web:3658aa3b99c79ccb316e97',
    messagingSenderId: '571856118326',
    projectId: 'cooking-game-cf5a9',
    authDomain: 'cooking-game-cf5a9.firebaseapp.com',
    storageBucket: 'cooking-game-cf5a9.firebasestorage.app',
    measurementId: 'G-WGFD6VL9XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJv8n9j6lvJ-AutJFsMHL6YN3XdUtJcRo',
    appId: '1:571856118326:android:a704a20abdfebd62316e97',
    messagingSenderId: '571856118326',
    projectId: 'cooking-game-cf5a9',
    storageBucket: 'cooking-game-cf5a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkXHPf7NfC0OVbxnUsp5-xcEu673ywUvU',
    appId: '1:571856118326:ios:90fcf2ae9f2c1d87316e97',
    messagingSenderId: '571856118326',
    projectId: 'cooking-game-cf5a9',
    storageBucket: 'cooking-game-cf5a9.firebasestorage.app',
    iosBundleId: 'com.example.cookingGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkXHPf7NfC0OVbxnUsp5-xcEu673ywUvU',
    appId: '1:571856118326:ios:90fcf2ae9f2c1d87316e97',
    messagingSenderId: '571856118326',
    projectId: 'cooking-game-cf5a9',
    storageBucket: 'cooking-game-cf5a9.firebasestorage.app',
    iosBundleId: 'com.example.cookingGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFtTFtOTfPCERjKlnOibTrTJywMNWsEI0',
    appId: '1:571856118326:web:03298e09f5f7d7c6316e97',
    messagingSenderId: '571856118326',
    projectId: 'cooking-game-cf5a9',
    authDomain: 'cooking-game-cf5a9.firebaseapp.com',
    storageBucket: 'cooking-game-cf5a9.firebasestorage.app',
    measurementId: 'G-KQ0VMJTRWZ',
  );
}
